### ISSUE TITLE
Success message issue join community popup

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Sungin-Internal--Feb21st-2022#1]
Bug - Not showing any success message when user subscribe.
Exp - Should show success message after clicking subscribe button.
Ref Link - https://drive.google.com/file/d/1j42BCmgJ5Oxn4nLt_fApb5JL1cU0VJjB/view

**Comment by devRaunakYadav** [comment]
![Uploading image.png…]()
It's showing

**Comment by ankitcedcoss** [comment]
Bug Fixed
