### ISSUE TITLE
Dynamic search dropdown not showing on desktop UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Sungin-Internal--Feb21st-2022#16]
Bug - Dynamic search dropdown not showing on desktop UI issue.
Exp - Dynamic search dropdown should be visible on desktop view also. As working on tab on mobile UI.
Ref Link - https://drive.google.com/file/d/1csMkPaA_j4NqlfK6zcAOlPjfQTd5w856/view

**Comment by devRaunakYadav** [comment]
I have already said to the client regarding this when we have an edit search bar, she's said no problem
Because there are too much customization so dynamic search is not working

**Comment by ankitcedcoss** [comment]
Closed on Not Req
