### ISSUE TITLE
Header icon callout popup UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Sungin-Internal--Feb21st-2022#18]
Bug - Account callout popup showing on cart icon.
Exp - Account callout popup should visible on account icon on header.
Ref Link - https://drive.google.com/file/d/1uODiy3NwaiajqRcDY_BVWBg8CSLYqB-i/view

**Comment by ui-anilrana** [comment]
![image](https://user-images.githubusercontent.com/100346531/169547240-77196fb4-01f4-4499-ac92-32a74a25c48f.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed - Popup not aligned properly. Need to align properly same as on cart.
- https://drive.google.com/file/d/1Jqh3CgwZxz42BCacnPaxnBgAuYjkYOKT/view

**Comment by ankitcedcoss** [comment]
Bgu Fixed
