### ISSUE TITLE
Check wishlist option missing on store

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Sungin-Internal--Feb21st-2022#20]
Bug 1 - No option available to check wishlist on store.
Exp - Can add wishlist icon on header to check wishlist section.
Ref List - https://drive.google.com/file/d/1yIKwe239Ajzshj4-IPHbH0MtPheBt5k1/view

Bug 2 - Add product to wishlist popup get hide behind to chatbot button.
Exp - Chat button should not overlap on wishlist popup.
Ref link - https://drive.google.com/file/d/1yIKwe239Ajzshj4-IPHbH0MtPheBt5k1/view

**Comment by devRaunakYadav** [comment]
![image](https://user-images.githubusercontent.com/86884638/169635779-4054413f-21a6-4167-a204-f2bb2ab3fd94.png)
added on footer as menu

**Comment by devRaunakYadav** [comment]
![image](https://user-images.githubusercontent.com/86884638/169636408-2ca83b27-9a70-47a0-bd43-8804d86b1452.png)
now on center

**Comment by ankitcedcoss** [comment]
Bug Fixed
