### ISSUE TITLE
Password Char length verification error issue.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Sungin-Internal--Feb21st-2022#27]
Bug - Password char length verification showing different on create account page and on reset password page.
Exp - Password char length should be visible same in validation on both pages.
Ref Link - https://drive.google.com/file/d/1wQit2JLx4UtunlBWVkgX11DQce7qmysV/view

**Comment by devRaunakYadav** [comment]
![image](https://user-images.githubusercontent.com/86884638/169636725-8a364464-dca0-4631-a932-c52e0d37d97a.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
