### ISSUE TITLE
Page heading text visibility issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Sungin-Internal--Feb21st-2022#3]
Bug - Page heading text not clearly visible on very landing pages.
Exp - Sugg - Can change heading color to black so that heading text get visible clear.
Ref Link - https://drive.google.com/file/d/1KWbw3QPTRqOd1Qe9WH71UyWTMdIbiA_L/view

**Comment by ui-anilrana** [comment]
Heading color as per client requirement
