### ISSUE TITLE
Collection page UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Sungin-Internal--Feb21st-2022#4]
Bug - Spacing issue between dropdown and text alignment issue.
Exp - Add spacings between downdown and text should be left aligned.
Ref Link - https://nimb.ws/vXh3GI
- https://nimb.ws/26f7IP

**Comment by ankitcedcoss** [comment]
Bug Not Fixed
![image](https://user-images.githubusercontent.com/100753159/169543847-4996f648-3fb2-4646-93cb-708a8a0d9721.png)

**Comment by ui-anilrana** [comment]
![Screenshot](https://user-images.githubusercontent.com/100346531/169546328-c21b7008-9f43-414b-a44c-2f2a17691ca5.png)



 already fixed

**Comment by ankitcedcoss** [comment]
Big Fixed
